{% set name = "pytest-cpp" %}
{% set version = "1.5.0" %}
{% set sha256 = "efb7eaac30f9f61515be181d04b70d80d60ce8871426f726ef1844e2db4f3353" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python
    - pytest

test:
  imports:
    - pytest_cpp

about:
  home: http://github.com/pytest-dev/pytest-cpp
  license: MIT
  license_file: LICENSE
  summary: Use pytest's runner to discover and execute C++ tests

extra:
  recipe-maintainers:
    - gqmelo
    - nicoddemus
