{% set name = "pytest-cpp" %}
{% set version = "2.3.0" %}
{% set sha256 = "37abfa693697940aed2e7c034698188dee3616183ad9b3f764f3b06aeb75ed4a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.7
    - pytest >=7.0

test:
  imports:
    - pytest_cpp

about:
  home: http://github.com/pytest-dev/pytest-cpp
  license: MIT
  license_file: LICENSE
  summary: Use pytest's runner to discover and execute C++ tests

extra:
  recipe-maintainers:
    - gqmelo
    - nicoddemus
