{% set name = "pytest-cpp" %}
{% set version = "2.0.0" %}
{% set sha256 = "6ccbf23fbdef49ab016086a94e127c8a8c9fc2663d40705702a5581c49a243cf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=2.7
    - pytest

test:
  imports:
    - pytest_cpp

about:
  home: http://github.com/pytest-dev/pytest-cpp
  license: MIT
  license_file: LICENSE
  summary: Use pytest's runner to discover and execute C++ tests

extra:
  recipe-maintainers:
    - gqmelo
    - nicoddemus
