{% set name = "pytest-cpp" %}
{% set version = "2.1.0" %}
{% set sha256 = "b21f93ff912bc6d1f3e0339dc06a7eacdaad0667e036a054a966c075d76973a4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.6
    - pytest

test:
  imports:
    - pytest_cpp

about:
  home: http://github.com/pytest-dev/pytest-cpp
  license: MIT
  license_file: LICENSE
  summary: Use pytest's runner to discover and execute C++ tests

extra:
  recipe-maintainers:
    - gqmelo
    - nicoddemus
