{% set name = "pytest-cpp" %}
{% set version = "2.6.0" %}
{% set sha256 = "c2f49d3c038539ac84786a94d852e4f4619c34c95979c2bc69c20b3bdf051d85" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - pytest

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytest_cpp

about:
  home: http://github.com/pytest-dev/pytest-cpp
  license: MIT
  license_file: LICENSE
  summary: "Use pytest's runner to discover and execute C++ tests"

extra:
  recipe-maintainers:
    - gqmelo
    - nicoddemus
