travis:
  secure:
    BINSTAR_TOKEN: EGNxyh2A+eSt64R7e9DpRveLTPje3IeH4l5qcg54YcRqKmjgxDVBtRjMD1cqCMyR+RUqNS9wxfieWF/jDHnl9DrWfv04G6MPfXX+wu7xwC2vc+2Fhk212KbfAG/XUMtEl8JZDV/pzQkx/rrSrdQAmsIp0iAqrgYPBk2g7FP9vhhSJzKLDFqFxu35qi7NIN425T0Qg2oD6ZVXpJK4ZB+/c7djT5Ce9metWc570m9edq8EovrQW+TaNZesHejAgC3rKmq9uqHuRGAuaIxSg4WdrhPDUzXzpckD9gUMa/pbHZlOy3GLygtlj0M8DYOSbIYCuoo8qIBqU57IZVKCkUsvjWvwOISeGlIvGiDTwm4hhKzjDrHfY9FJ/tqSARTd+qfL+hDBubJBA4aqUzl8BDDZmcv3pBqqKRHE3sWaZttori11y8mMv89bww8AQTP+dTENLqjWRMRjX/boDNvldJ+2NQgJ8l3x4EueQGktO1kMgHo7f3s6mDUhz8YSjzCtoRmWA+7RLHVrZdvAjxNYL8gUvWsRd2wz/gK4MvQwaZCPOYIthvwAIexX3HrJ/zPnbqIn8zmvi76djnHCvdMqk/Qr2nuFy5fz3AZl+h/ueA7GroNtUD9bhOKEcG/o1V3vFOKel5/HrJVuEXEhrHXFjf0cdIIgG8xyKQnArZZaKZHM274=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
