travis:
  secure:
    BINSTAR_TOKEN: PfaoRIc+zyqN2Wr/yh/puKIrAiTgWTJZ2bCp8xp38/LxyhGFxl5Ziz+2ALGA6HIERpMtbJfXryAsjQyrpg3gy/p2Vgt/ITBCqBMZ6X9TATNqOTR8U9fArOMFQIa/yvyw8btG4QCuX2S9YW548HrOXdQFfovfAflL5CRrlbiI1EW4o9BoBgnWB523Vbk3XMxgckE7fMAEDFnyGWIa0TCc5shTg2vrxm27b2txgni57Uph+KeMlWHiJHXQmMyoFhnw9VfpgLS4QuC0zMBiZDsrtRXAAO2XSdQB/cH39jobohYfNGtk+7s9M2YKBqUxx7wFoIrutzGF9ZiRTVBfqFc4Ijzys7J7AAM7Wl+lXre6BP+W9G0xrxdKMh4qlUbApkfK2lLtwdTnVrfwlyF74VLP51gYLIZBdNnW8C2DFyW5TSQIzWHdMfHq9jX72VqeVCwZxl+Aub8EaMfe39rChz099uTzY7e0814aNokAfMH1xPGTboxQ4ZAH2n2QS1yeWcZQSoMfwvafc/qIhywTF4XvDO+KO02Z1MqKgQY81pYLK1mImeeEYni1Fo2TUuP7Nh1+2xzPRgZI+mT+HaSxDyF4HSh2mM5srL8Kz3q2brauytKUUA3J0Y68fIjChGj3CZXy+//pCe+oPBY7F4vRsJrubkJTgY3Km1HvqlgTVOA73L0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
